/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    screens: {
      xm: "300px",
      sm: "420px",
      md: "1024px",
      lg: "1280px",
    },
    extend: {
      colors: {
        primary: {
          50: "#f2fbf9",
          100: "#d3f4ee",
          200: "#8de2d4",
          300: "#72d6c9",
          400: "#2ca096",
          500: "#21807b",
          600: "#1e6763",
          700: "#1c5351",
          800: "#1c5351",
        },
        bgColor: {
          10: "#214544",
          20: "#102F2E",
        },
        lemon: {
          10: "#15d798",
          20: "#10b981",
        },
        textColor: {
          10: "#ABE4E4",
        },
      },
      fontSize: {
        title: "30px",
        description: "20px",
        cardTitle: "44px",
        cardDescription: "12px",
      },
      fontFamily: {
        body: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
      },
    },
  },
  plugins: [],
};
