/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    // screens: {
    //   xm: "300px",
    //   sm: "420px",
    //   md: "1024px",
    //   lg: "1280px",
    // },
    extend: {
      colors: {
        primary: {
          50: "#f3f8f7",
          100: "#e0eded",
          200: "#c1dcdc",
          300: "#9ac6c6",
          400: "#2ca096",
          500: "#4e898c",
          600: "#447176",
          700: "#3c5e62",
          800: "#374f53",
        },
        bgColor: {
          10: "#9ac6c6",
          20: "#447176",
        },
        lemon: {
          10: "#314448",
          20: "#1d2c2f",
        },
        textColor: {
          10: "#ABE4E4",
        },
      },
      fontSize: {
        title: "30px",
        description: "20px",
        cardTitle: "44px",
        cardDescription: "12px",
      },
      fontFamily: {
        body: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
      },
    },
  },
  plugins: [],
};
